### ISSUE TITLE
Import AutomationML into AASX - no reaction on UI, no error log

### ISSUE THREAD

**Issue by ruedigerfritz** [admin-shell-io/aasx-package-explorer#226]
**Describe the bug**
I try to import an .aml file, but import fails - no reaction on the UI

**To Reproduce**
I tried various starting points: 
- new, but empty package
- new, but empty AAS
- AAS with new submodel ...
in each case, no reaction.
Also tried to debug AMLImport.cs, but I can't help myself as I do not know how the expected behaviour should be??

**Expected behavior**
That's my challenge - I don't know how an imported .aml should materialize in the PackageExplorer??

Big thanks for your help and
kind regards,
Ruediger

**Comment by MichaelHoffmeisterFesto** [comment]
Hello Ruediger,
the correct procedure is: new package, then import an AML.
Note: only AMLs which are compliant to the AAS/AML-mapping will be imported, not general AML.
The Result would be a AAS, which is near to the exported AAS (but e.g. no file contents).
I've checked the import and found two bugs, which I corrected in the branch MIHO/EnhanceAmlImport.
The first bug was associated with the change of DataSpecfications; the 2nd was introduced by an "improvent" handling of "AdequateTypes" in SubmodelElementWrapper. 
The test-file, which we used back in the days ("Example_AAS_ServoDCMotor.aml"), works now.
However, I realized, that new SubmodelElements (such as Entities, AnnotatedRelations and more) are right now not covered by the AML import/ export. Consequently, there is room for improvement.
Currently, the branch MIHO/EnhanceAmlImport is not already PRed back into master.
Best,
Michael

**Comment by MichaelHoffmeisterFesto** [comment]
Currently working on adding more SubmodelElement types (Entity, AnnotatedRelationshipElement).
BTW: If you want to have a detailed import log, you can use the AasxGenerate / AasxToolkit load function.

**Comment by MichaelHoffmeisterFesto** [comment]
I have also added RangeElement; the "content-less" SubmodelElements such as Capability, BasicEvent will work out of the box.
Still in MIHO/EnhanceAmlImport; will aim to integrated the branch via PR soon.

**Comment by MichaelHoffmeisterFesto** [comment]
The AML import/ export should be available in master & current realease.
UI interaction is still minimal.
AasxToolkit enables a lot of debug messages on command line level.
