### ISSUE TITLE
Link to Samples in Readme not working

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aasx-package-explorer#240]
In Readme.md it is stated "We provide a couple of sample admin shells (packaged as .aasx) for you to test and play with the software at: http://www.admin-shell-io.com/samples/". However, the link to http://www.admin-shell-io.com/samples/ is not available.
Probably the sample files were moved to another location?

**Comment by mristin** [comment]
Hi @BirgitBoss,
The link works for me -- could you please double-check?

**Comment by BirgitBoss** [comment]
I double-checked, when using a different browser it works, sorry. I need to check why it does not work with Mozilla... Is it possible to download all samples at once?

**Comment by mristin** [comment]
You can use `src/DownloadSamples.ps1`; would that work for you?

I'll close the issue -- please feel free to re-open if the problem persists.

**Comment by BirgitBoss** [comment]
Thanks, @mristin works fine!
