### ISSUE TITLE
Workspace->Plugins->New Submodel - misleading error message "AASX Package needs to be open"

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aasx-package-explorer#243]
When selecting Workspace.Plugins.New Submodel I always get the error message that "an aasx package needs to be open". I just click "ok" and then continue selecting the submodel plugin and everything is fine.

That is, the error message is not valid and misleading.

**Comment by MichaelHoffmeisterFesto** [comment]
This check occurred for 6 menu commands, but did not result in an abort of the command. 
For 5 commands, I have modified the behavior, that the package environment needs to exist, but not to be open (that is, it could be a new one). If it does not exists, the command will be aborted.
For the conversion of Submodels, it is also required that the environment is writable as file, as supplementary packages might be added to the package by the conversion.

**Comment by MichaelHoffmeisterFesto** [comment]
The branch is: MIHO/FixNewSubmodelDialogue
The PR is: [link](https://github.com/admin-shell-io/aasx-package-explorer/pull/262)

**Comment by BirgitBoss** [comment]
Fixed, issue can be closed.
