### ISSUE TITLE
invalid XML for "qualifier" - probably due to ambiguous naming

### ISSUE THREAD

**Issue by br-iosb** [admin-shell-io/aasx-package-explorer#264]
I opened a .aasx file containing a SubmodelElementCollection with two qualifiers. Then I exported it as .xml to open it with a XML editor.
The validation failed for mentioned "qualifier"-elements!

```xml
<aas:qualifier>
  <aas:qualifier>
    <aas:type>cardinality</aas:type>
    <aas:valueType />
    <aas:value>0..1</aas:value>
  </aas:qualifier>
  <aas:qualifier> **//FAILED HERE!**
    <aas:type>cardinality</aas:type>
    <aas:valueType />
    <aas:value>0..1</aas:value>
  </aas:qualifier>
</aas:qualifier>
```
After analysing the XSD I think it should look like:
```xml
<aas:qualifier>
	<aas:qualifier>
		<aas:type>cardinality</aas:type>
		<aas:valueType/>
		<aas:value>0..1</aas:value>
	</aas:qualifier>
</aas:qualifier>
<aas:qualifier>
	<aas:qualifier>
		<aas:type>cardinality</aas:type>
		<aas:valueType/>
		<aas:value>0..1</aas:value>
	</aas:qualifier>
</aas:qualifier>
```
This is confusing because of the way the XSD is naming the elements - please note the duplicated "qualifier" naming:
```xml
...
<group name="qualifiable">
	<sequence>
		<element maxOccurs="unbounded" minOccurs="0" name="qualifier" type="aas:constraint_t"/>
	</sequence>
</group>
...
<complexType name="constraint_t">
	<choice>
		<element maxOccurs="1" minOccurs="0" name="formula" type="aas:formula_t"/>
		<element maxOccurs="1" minOccurs="0" name="qualifier" type="aas:qualifier_t"/>
	</choice>
</complexType>
...
```
A clearer solution seems to be:
```xml
<group name="qualifiable">
	<sequence>
		<element maxOccurs="unbounded" minOccurs="0" name="constraint" type="aas:constraint_t"/>
	</sequence>
</group>

<complexType name="constraint_t">
	<choice>
		<element maxOccurs="1" minOccurs="0" name="formula" type="aas:formula_t"/>
		<element maxOccurs="1" minOccurs="0" name="qualifier" type="aas:qualifier_t"/>
	</choice>
</complexType>
```
Then the XML would be:
```xml
<aas:constraint>
	<aas:qualifier>
		<aas:type>cardinality</aas:type>
		<aas:valueType/>
		<aas:value>0..1</aas:value>
	</aas:qualifier>
</aas:constraint>
<aas:constraint>
	<aas:qualifier>
		<aas:type>cardinality</aas:type>
		<aas:valueType/>
		<aas:value>0..1</aas:value>
	</aas:qualifier>
</aas:constraint>
```

**Comment by BirgitBoss** [comment]
Thanks for the comment. This will be fixed in the next version of the xml schema (expected in November this year). Fixing during production phase is not downward-compatible.

**Comment by JoergWende** [comment]
What about this structure ?
J.
	<group name="qualifiable">
		<sequence>
			<element maxOccurs="1" minOccurs="0" name="qualifier" type="aas:constraints_t"></element>
		</sequence>
	</group>
      <complexType name="constraints_t">
		<sequence>
			<element name="constraint" type="aas:constraint_t" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

**Comment by BirgitBoss** [comment]
This is the proposal I got from Michael:
  
     <group name="qualifiable">
             <sequence>
                    <element maxOccurs="unbounded" minOccurs="0" name="qualifiers" type="aas:constraint_t"/>
             </sequence>
       </group>
 

An xml instance would look like this:
             
              <qualifiers>
                  <qualifier><Type>…</Type></qualifier>
                  <qualifier><Type>…</Type></qualifier>
                 <formula>…</formula>
              </qualifiers>

this would be also what I expect

**Comment by JoergWende** [comment]
ok - changed the schema accordingly ..
J.

**Comment by BirgitBoss** [comment]
Thanks, Jörg, In V3.0RC01 xsd schema it is now realized as

	<group name="qualifiable">
		<sequence>
			<element maxOccurs="1" minOccurs="0" name="qualifiers" type="aas:constraints_t"/>
		</sequence>
	</group>
	<complexType name="constraints_t">
		<choice>
			<element maxOccurs="unbounded" minOccurs="0" name="formula" type="aas:formula_t"/>
			<element maxOccurs="unbounded" minOccurs="0" name="qualifier" type="aas:qualifier_t"/>
		</choice>
	</complexType

I am cloing this issue. Please feel free to reopen it if there are still open issues.
