### ISSUE TITLE
404 error for "Building the Solution" link in documentation

### ISSUE THREAD

**Issue by krahlro-sick** [admin-shell-io/aasx-package-explorer#332]
The link "Building the Solution" in the developer documentation leads to a 404 error page.

**To Reproduce**
1. Go to https://admin-shell-io.github.io/aasx-package-explorer/devdoc/getting-started/intro.html
2. Click on 'Building the Solution.'
3. See the error page

**Expected behavior**
Instead of the error page, a guide on how to build the solution is displayed.

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280.141

**Comment by mristin** [comment]
Thanks for reporting, @krahlro-sick !

I try to have a look at it tomorrow (Wednesday).

**Comment by krahlro-sick** [comment]
I just had another look at the Git history.  Apparently. you refactored the file content into other files without removing the navigation entry in https://github.com/admin-shell-io/aasx-package-explorer/commit/ce3e4d3b1456e5686fcacefb8284e5a75d7643fe.

**Comment by mristin** [comment]
@krahlro-sick thanks again for spotting this one and please let me know if you find more errors in the docs!
