### ISSUE TITLE
Only report offending files in CheckBiteSized.ps1

### ISSUE THREAD

**Issue by krahlro-sick** [admin-shell-io/aasx-package-explorer#346]
If there is a file with an overlong line, I have to find the few FAIL lines within several hundred OK lines in the output of `CheckBiteSized.ps1`.  It would be more convenient if the script would only show the offending files per default.  If necessary, a `--verbose` flag could be added that lists all files.

**Comment by mristin** [comment]
Hi @krahlro-sick ,
I'll try to implement that this Wednesday.
