### ISSUE TITLE
Support for metamodel v3.0

### ISSUE THREAD

**Issue by mmarseu** [admin-shell-io/aasx-package-explorer#365]
Are there plans to support v3.0 of the metamodel anytime soon? Or will the implementation be postponed until a final version is released?

I'm asking because I'm working on a project where we'd like to get working on supporting v3.0 given the current release candidate but we're using the AASX Package Explorer as a reference implementation whenever any parts of the metamodel are unclear.

**Comment by BirgitBoss** [comment]
Sorry for the late answer. There are plans to update the aasx package explorer to V3.0RC02 in 2022.
