### ISSUE TITLE
Cannot Find Submodel

### ISSUE THREAD

**Issue by Therrow** [admin-shell-io/aasx-package-explorer#418]
**Describe the bug**
After Creating any arbitrary AAS, after changing the editing mode (in AND out), i recieve the error message: "Cannot find some submodel.

**To Reproduce**
I followed the described Steps in the Screencasts to create a submodel. But at any point of the creation process i recieve the Error Message after swithing into the edit Mode or out of it.
This does not happen, if i change the Edit mode in a demo-version.

**Comment by BirgitBoss** [comment]
You still need advice or can this issue be closed?

**Comment by Therrow** [comment]
It can be closed i think
