### ISSUE TITLE
Inserting AASX files from AASX Package Explorer into the AASX server

### ISSUE THREAD

**Issue by furlanvitor** [admin-shell-io/aasx-package-explorer#420]
**Describe the bug**
I started the demo  of AASX Server (the one with the AAS of an example Servo DC motor), then I connected the AASX Package Explorer to this HTTP/REST repository and I could see the example of AAS that it contains. When I try to insert a new AAS into the server it doesn't work. AASX Package Explorer displays the server's AAS list as if it was added, but it is not actually loaded into the repository. Also, when I try to open this AAS that I just added, the AASX Package Explorer application closes.

**To Reproduce**
1. Run AASX server in localhost (windows: startForDemo.bat)
2. Open AASX Package Explorer and connect to the server (file -> AASX File Repository -> connect HTTP/REST repository)
3. In the repository tab (down left region), click “Add multiple AASX files”. Alternatively, open another AASX file and click “Add current AAS”.
4. Verify that the AASX is listed as if it was part of the repository.
5. Click twice to open the AASX file you just added to the repository. The AASX Package Explorer closes. If you check aasxs folder of the repository, the AASX file you added is not there.

**Expected behavior**
I expected to really add the AASX file to the repository and be able to open it from AASX Package Explorer.

**Screenshots**
![image](https://user-images.githubusercontent.com/69992900/139752968-0bc289dd-1ac3-410e-bdcc-9f75c6e68f81.png)
![image](https://user-images.githubusercontent.com/69992900/139753038-7cd7eacc-8f19-438e-968e-21d6f58c3a90.png)
![image](https://user-images.githubusercontent.com/69992900/139753085-f5c7d318-d05c-45f3-951b-68f828248600.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: not applicable
 - Version: not applicable

**Additional context**

**Comment by aorzelskiGH** [comment]
Adding an AAS by REST is currently not implemented. This will be added when updating to the standardized REST API which will be released end of November.

**Comment by furlanvitor** [comment]
Thank you very much for your reply!
