### ISSUE TITLE
CheckFormat.ps1 and FormatCode.ps1 fail when .NET 6 is installed

### ISSUE THREAD

**Issue by mmarseu** [admin-shell-io/aasx-package-explorer#474]
**Describe the bug**
The AASX Package Explorer is using *dotnet core 3.1*, however unless a [`global.json`](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) config file is present, the dotnet CLI will always run commands using the latest installed version of the SDK. With .NET 6 that becomes a problem, because starting with this version, the CLI bundles a more current version of the dotnet-format tool than is used in this project. The bundled version has changed some options, notable `--check` is now `--verify-no-changes`. Crucially, the dotnet 6 CLI prefers the bundled version over the installed tool.

**To Reproduce**
1. Install .NET 6
2. Run `dotnet format --check`. It will fail.

**Solution**
One possible solution to this problem would be to add a `global.json`, which would instruct the dotnet CLI to run commands in version 3.1.

Another would be to update the dotnet-format version in `src/.config/dotnet-tools.json` (and the scripts using this command) to a more current version.

**Comment by br-iosb** [comment]
Correct!
We have already tested the use of global.json, see https://github.com/admin-shell-io/aasx-package-explorer/blob/jtikekar/asp.net/restapi/global.json
The branch has already a PR but checks are failing but hopefully will be resolved very soon.
