### ISSUE TITLE
Error: Unhandled exception | SAMM CLI generated AASX of BatteryPass cannot be opened in Package Explorer

### ISSUE THREAD

**Issue by chris-volk** [admin-shell-io/aasx-package-explorer#641]
**Describe the bug**
SAMM CLI generated AASX of BatteryPass cannot be opened in Package Explorer

**To Reproduce**
1. Rename [BatteryPass.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/12590204/BatteryPass.zip) to *.aasx
2. Install https://github.com/admin-shell-io/aasx-package-explorer/releases/download/v2023-09-12.alpha/aasx-package-explorer.2023-09-12.alpha.zip from https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-09-12.alpha and open it
4. File->Open -> Choose BatteryPass.aasx

**Expected behavior**

- BatteryPass.aasx is opened with a submodel template that corresponds to the BatteryPass Aspect Model from catena-x at https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl .
- Alternatively, if the file BatteryPass.aasx is not a valid aasx (which may or may not be the case, I would like to know please :-) ), I would like a user error that clearly states that I have tried to import an invalid file (ideally with an intention revealing error message that helps me understand what is wrong)

**Actual behavior**
- "Error: Unhandled exception"
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/71717528/f7622524-e939-4b77-bbcc-14b07a8600c2)
noteworth that the mentioned version 1.0.0.0 is not the actual version of the software
- the log content below for diagnosis:
[BatteryPass.aasx_error-log.txt](https://github.com/admin-shell-io/aasx-package-explorer/files/12590275/BatteryPass.aasx_error-log.txt)

**Screenshots**

**Additional context**

BatteryPass.aasx was created via SAMM CLI from the BatteryPass aspect model by catena-x using:

- Downloaded https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/3.0.1/BatteryPass.ttl and referenced models and move them in the correct folder structure according to their namespaces as defined on https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html#models-directory-structure 
- The zipped version of this can be received here for convenience:
[io.catenax.battery.battery_pass.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/12590224/io.catenax.battery.battery_pass.zip)
- Ran the samm cli with this input and specify to aas and file format aasx as follows:
 `C:\Program Files\RedHat\java-17-openjdk\bin>java -jar "C:\samm-cli-2.2.3.jar" aspect "C:\Users\vol1sgh\aspect-model-editor\models\io.catenax.battery.battery_pass\3.0.1\BatteryPass.ttl" to aas -o U:\BatteryPass.aasx -f aasx`
 
 Thanks for looking into this issue and feel free to get in touch with your neighbor project from the Eclipse Semantic Modeling Framework if you have points to discuss recarding how this aasx was created or any other topics.

**Comment by agg3fe** [comment]
Hi Team,
I want to mention that I am also facing same error while trying to import the aasx files into package explorer. I have tried with multiple files, example [this](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.week_based_capacity_group/2.0.0/gen/WeekBasedCapacityGroup.aasx) , but faces same error every time, which says `ID is not a valid XSD ID`.
It is getting important for us to import the aasx file into the package explorer, Could you please help here to resolve this issue.
Please contact me if you need further information on this. Thank you.

**Comment by BirgitBoss** [comment]
This issue will be solved in https://github.com/eclipse-esmf/esmf-sdk/issues/488. This is why I will close this one.
If needed a new issue for support of relative paths in .aasx should be added.

Still open: Versioning in error message and improvement of error messages
