### ISSUE TITLE
Unsupported on VS 2022 community version (also happen in VS 2019 community version)

### ISSUE THREAD

**Issue by jeffenhuang** [admin-shell-io/aasx-package-explorer#652]
**Describe the bug**
when opening the project solution, a dialog popup indicates unsupported.

**To Reproduce**
1. Go to 'aasx_package_explorer\src'
2. Double click on 'AasxPackageExplorer.sln'
3. See unsupported information as shown below.

**Expected behavior**

**Screenshots**
![2023-10-06 13_31_42-Review Project And Solution Changes](https://github.com/admin-shell-io/aasx-package-explorer/assets/3396011/150d1384-0149-479f-83c6-60ec44bc56ed)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - IDE: Microsoft Visual Studio Community 2022 (64-bit) - Current
  Version 17.7.4
  Microsoft Visual Studio Community 2022
  Version 17.7.4
  VisualStudio.17.Release/17.7.4+34031.279
  Microsoft .NET Framework
  Version 4.8.04084
  
  Installed Version: Community
  
  Visual C++ 2022   00482-90000-00000-AA541
  Microsoft Visual C++ 2022
  
  ASP.NET and Web Tools   17.7.273.65229
  ASP.NET and Web Tools
  
  Azure App Service Tools v3.0.0   17.7.273.65229
  Azure App Service Tools v3.0.0
  
  C# Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
  C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
  
  Cookiecutter   17.0.23189.3
  Provides tools for finding, instantiating and customizing templates in cookiecutter format.
  
  Extensibility Message Bus   1.4.34 (main@d5ab18b)
  Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
  
  Microsoft JVM Debugger   1.0
  Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
  
  Mono Debugging for Visual Studio   17.7.27 (547ea6f)
  Support for debugging Mono processes with Visual Studio.
  
  NuGet Package Manager   6.7.0
  NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
  
  Python - Profiling support   17.0.23189.3
  Profiling support for Python projects.
  
  Python with Pylance   17.0.23189.3
  Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
  
  Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
  Provides languages services for ASP.NET Core Razor.
  
  Test Adapter for Boost.Test   1.0
  Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.
  
  Test Adapter for Google Test   1.0
  Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.
  
  TypeScript Tools   17.0.20829.2001
  TypeScript Tools for Microsoft Visual Studio
  
  Visual Basic Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
  Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
  
  Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
  Microsoft Visual F# Tools
  
  Visual Studio IntelliCode   2.2
  AI-assisted development for Visual Studio.
  
  VisualStudio.DeviceLog   1.0
  Information about my package
  
  VisualStudio.Mac   1.0
  Mac Extension for Visual Studio
  
  VSPackage Extension   1.0
  VSPackage Visual Studio Extension Detailed Info
  
  Xamarin   17.7.0.216 (d17-7@133ddef)
  Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
  
  Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
  Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
  
  Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
  Xamarin.Android Reference Assemblies and MSBuild support.
      Mono: d9a6e87
      Java.Interop: xamarin/java.interop/d17-5@149d70fe
      SQLite: xamarin/sqlite/3.40.1@68c69d8
      Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
copied information about unsupported:
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them.
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - AasxPackageExplorerSetup, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AASXPackageExplorerSetup\AasxPackageExplorerSetup.wixproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - AasxPackageExplorer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPackageExplorer\AasxPackageExplorer.csproj"
	 - AasxToolkit, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxToolkit\AasxToolkit.csproj"
	 - AasxWpfControlLibrary, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxWpfControlLibrary\AasxWpfControlLibrary.csproj"
	 - AasxRestServerLibrary, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxRestServerLibrary\AasxRestServerLibrary.csproj"
	 - AasxRestConsoleServer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxRestConsoleServer\AasxRestConsoleServer.csproj"
	 - AasxIntegrationBase, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxIntegrationBase\AasxIntegrationBase.csproj"
	 - AasxIntegrationEmptySample, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxIntegrationEmptySample\AasxIntegrationEmptySample.csproj"
	 - AasxAmlImExport, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxAmlImExport\AasxAmlImExport.csproj"
	 - AasxMqtt, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxMqtt\AasxMqtt.csproj"
	 - AasxMqttClient, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxMqttClient\AasxMqttClient.csproj"
	 - AasxPluginBomStructure, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginBomStructure\AasxPluginBomStructure.csproj"
	 - AasxPredefinedConcepts, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPredefinedConcepts\AasxPredefinedConcepts.csproj"
	 - AasxPluginDocumentShelf, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginDocumentShelf\AasxPluginDocumentShelf.csproj"
	 - AasxIntegrationBaseWpf, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxIntegrationBaseWpf\AasxIntegrationBaseWpf.csproj"
	 - AasxPluginGenericForms, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginGenericForms\AasxPluginGenericForms.csproj"
	 - MsaglWpfControl, "C:\Users\hwb20103\Github\aasx-package-explorer\src\MsaglWpfControl\MsaglWpfControl.csproj"
	 - AasxPluginExportTable, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginExportTable\AasxPluginExportTable.csproj"
	 - AasxPluginWebBrowser, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginWebBrowser\AasxPluginWebBrowser.csproj"
	 - AasxPluginTechnicalData, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginTechnicalData\AasxPluginTechnicalData.csproj"
	 - Solution Items, "Solution Items"
	 - AasxDictionaryImport, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxDictionaryImport\AasxDictionaryImport.csproj"
	 - AasxSignature, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxSignature\AasxSignature.csproj"
	 - AasxOpenidClient, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxOpenidClient\AasxOpenidClient.csproj"
	 - AasxCsharpLibrary.Tests, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxCsharpLibrary.Tests\AasxCsharpLibrary.Tests.csproj"
	 - BaseCode, "BaseCode"
	 - AasxDictionaryImport.Tests, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxDictionaryImport.Tests\AasxDictionaryImport.Tests.csproj"
	 - FunctionalLibs, "FunctionalLibs"
	 - Plugins, "Plugins"
	 - ProgsCommandLine, "ProgsCommandLine"
	 - ProgsUserInterface, "ProgsUserInterface"
	 - DataStore, "DataStore"
	 - WpfMtpControl, "C:\Users\hwb20103\Github\aasx-package-explorer\src\WpfMtpControl\WpfMtpControl.csproj"
	 - AasxPluginMtpViewer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginMtpViewer\AasxPluginMtpViewer.csproj"
	 - WpfMtpVisuViewer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\WpfMtpVisuViewer\WpfMtpVisuViewer.csproj"
	 - FunctionalUiLibs, "FunctionalUiLibs"
	 - AasxUaNetServer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxUaNetServer\AasxUaNetServer.csproj"
	 - AasxPluginUaNetServer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginUaNetServer\AasxPluginUaNetServer.csproj"
	 - AasxPluginUaNetClient, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginUaNetClient\AasxPluginUaNetClient.csproj"
	 - AasxUaNetConsoleServer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxUaNetConsoleServer\AasxUaNetConsoleServer.csproj"
	 - UserSpecific, "UserSpecific"
	 - WpfXamlTool, "C:\Users\hwb20103\Github\aasx-package-explorer\src\WpfXamlTool\WpfXamlTool.csproj"
	 - AasxPluginImageMap, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginImageMap\AasxPluginImageMap.csproj"
	 - AasxToolkit.Tests, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxToolkit.Tests\AasxToolkit.Tests.csproj"
	 - AasxPackageExplorer.GuiTests, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPackageExplorer.GuiTests\AasxPackageExplorer.GuiTests.csproj"
	 - AasxPluginAdvancedTextEditor, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginAdvancedTextEditor\AasxPluginAdvancedTextEditor.csproj"
	 - AasxPackageExplorer.Tests, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPackageExplorer.Tests\AasxPackageExplorer.Tests.csproj"
	 - AasxPluginPlotting, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginPlotting\AasxPluginPlotting.csproj"
	 - AasxFormatCst, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxFormatCst\AasxFormatCst.csproj"
	 - AasxPluginSmdExporter, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginSmdExporter\AasxPluginSmdExporter.csproj"
	 - AasxPackageLogic, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPackageLogic\AasxPackageLogic.csproj"
	 - AnyUi, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AnyUi\AnyUi.csproj"
	 - BlazorUI, "C:\Users\hwb20103\Github\aasx-package-explorer\src\BlazorUI\BlazorUI.csproj"
	 - SSIExtension, "C:\Users\hwb20103\Github\aasx-package-explorer\src\SSIExtension\SSIExtension.csproj"
	 - AasxPluginKnownSubmodels, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginKnownSubmodels\AasxPluginKnownSubmodels.csproj"
	 - UIComponents.Flags.Blazor, "C:\Users\hwb20103\Github\aasx-package-explorer\src\UIComponents.Flags.Blazor\UIComponents.Flags.Blazor.csproj"
	 - AasxIntegrationBaseGdi, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxIntegrationBaseGdi\AasxIntegrationBaseGdi.csproj"
	 - AasxFileServerRestLibrary, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxFileServerRestLibrary\AasxFileServerRestLibrary.csproj"
	 - AasxBammRdfImExport, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxBammRdfImExport\AasxBammRdfImExport.csproj"
	 - jsoncanonicalizer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\jsoncanonicalizer\jsoncanonicalizer.csproj"
	 - es6numberserializer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\es6numberserializer\es6numberserializer.csproj"
	 - Setup, "Setup"
	 - Projektmappenelemente, "Projektmappenelemente"
	 - AasxSchemaExport, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxSchemaExport\AasxSchemaExport.csproj"
	 - BlazorExplorer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\BlazorExplorer\BlazorExplorer.csproj"
	 - AasCore.Aas3_0, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasCore.Aas3_0\AasCore.Aas3_0.csproj"
	 - AasxCsharpLibrary, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxCsharpLibrary\AasxCsharpLibrary.csproj"
	 - AasxPluginDigitalNameplate, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginDigitalNameplate\AasxPluginDigitalNameplate.csproj"
	 - AasxPluginContactInformation, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPluginContactInformation\AasxPluginContactInformation.csproj"
	 - AasxPackageExplorer, "C:\Users\hwb20103\Github\aasx-package-explorer\src\AasxPackageExplorer.sln"
	 - , ""

**Comment by Kaz040** [comment]
Hi, May I ask how you solved this issue, I am experiencing the same problem
