### ISSUE TITLE
AASX Package Explorer can't load *.aasx file where Part URI start without a forward slash

### ISSUE THREAD

**Issue by jannisjung** [admin-shell-io/aasx-package-explorer#654]
(1) [AASX Package Explorer v2023-09-12.alpha](https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-09-12.alpha) fails to load an *.aasx file with a Target-Attribure  of a Relationship-Element in a *.rels file that does not start with a forward slash. If a path doesn't start with a leading slash, amongst others, the Error Message `Part URI must start with a forward slash.` is displayed.
-> The aasx specification [SPOT Part5 AASX Package File Format](https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01005-3-0_SpecificationAssetAdministrationShell_Part5_AASXPackageFileFormat.pdf) references ISO/IEC 29500-2 [ECMA Office Open XML file formats -> Part 2](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/).
Here, paths with no leading slash are explicitly allowed (see 6.4.3.3 No leading slash). 
(2) Further more the AASX Package Explorer seems to expect paths, given in target attribute, always to be relative to the root directory (aasx/) which leads to unexpected behaviour as one would expect a relative path to be relative to the current directory.  
(see 6.5.3.4 Relationship element of ISO/IEC 29500-2)

**To Reproduce**
1. download the file [bugDemoAASX.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/12870057/bugDemoAASX.zip)
2. Adjust the file-ending to `.aasx` 
3. try opening the file in the AASX Package Explorer

**Expected behavior**
AASX Package Explorer can load the file

**Actual behavior**
AASX Package Explorer fails to load the file

**Additional context**
The file is structured like this:
```
bugDemoAASX.aasx
├── _rels
│   └── .rels
├── aasx
│   ├── _rels
│   │   └── aasx-origin.rels
│   ├── xml
│   │   └── content.xml
│   └── aasx-origin
├── docProps
│   └── core.xml
└── [Content_Types].xml
```
The File `bugDemoAASX.aasx/_rels/.rels` file contains a Relationship Target `aasx/aasx-origin`
The File  `bugDemoAASX.aasx/aasx/_rels/aasx-origin.rels` contains a Relationship Target `xml/content.xml`

Both Target paths can be resolved with a prefix forward slash `/`. The Target path of the `aasx-origin.rels` file additionally has to be prefixed with `/aasx` to be accepted by the AASX Package Explorer.

Studying the ISO/IEC 29500-2 spec, we understand that internal relative paths should be relative to the the parent directory of the _rels folder.

A resolved version of the BugDemo.aasx file, that works with the current Version of the AASX Package Explorer ( v2023-09-12.alpha) would be [resolvedBugDemoAASX.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/12870466/resolvedBugDemoAASX.zip) (file endig has to be adjusted to .aasx)
In our eyes, according to the spec, the provided [bugDemoAASX.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/12870057/bugDemoAASX.zip) file should work as well.

This is related to https://github.com/eclipse-aas4j/aas4j/issues/158

**Comment by BirgitBoss** [comment]
In Part 5 Chapter 5.4 File Name Conventions it is stated that `/aasx` shall be the common prefix for all files containing aasx package specific information. So relative pathes seem not be conformant to the specification Part 5 V3.0.

**Comment by FrankSchnicke** [comment]
The AASX produced by AAS4J is already structured in the way specified in Part 5. The issue is not with the structure of the AASX but with the resolution mechanism that the Package Explorer is using to find the target of a relationship. 

According to the OPC standard the target may be a relative or an absolute path (absolute paths being identified by a leading slash). The Package Explorer is only able to handle absolute paths and tries to handle any path as absolute path.

**Comment by BirgitBoss** [comment]
Part 5 is not supporting the complete specification of the OPC standard but only a subset. This is exactly what I am saying. Part 5 is requiring absolute paths.
