### ISSUE TITLE
Not able to see 'Asset' option under Environment

### ISSUE THREAD

**Issue by rushikesh0410** [admin-shell-io/aasx-package-explorer#677]
### Discussed in https://github.com/admin-shell-io/aasx-package-explorer/discussions/672

<div type='discussions-op-text'>

<sup>Originally posted by **rushikesh0410** December 10, 2023</sup>
Hi Community,
I am relatively new to aasx package explorer and have just installed latest release of AASX package explorer.

However, I am not able to see the Asset option under Environment. 

Right now, only options I see under Environment are, AdministrationShell, All Submodels and ConceptDescription

I would be very thankful if someone could help me out in this regard.

Thanking you,
best regards,
Rushikesh
  </div>

**Comment by BirgitBoss** [comment]
There is no stand-alone Asset any longer (i.e. Assets are no Identifiables any longer). It is _AssetAdministrationShell/assetInformation_. So you can edit the fields for asset information directly in the Asset Administration Shell object.

Please feel free to re-open the issue if your questions is not answered.
