### ISSUE TITLE
[BUG] SML orderRelevant cannot be set to false

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aasx-package-explorer#685]
**Describe the bug**
The default for SubmodelElementList/orderRelevant is True. 
It is not possible to set orderRelevant to False in the explorer.
Generated xml is ok, if field is not set or set (in both cases it would be true)

**To Reproduce**
1. Create SML within a Submodel
2. try to set orderRelevant to false 
3. check for generated xml

**Screenshots**
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/59824205/30cb93de-1806-47ab-a7bd-623b113051a8)

**Comment by AlexanderWollbrink** [comment]
Could not reproduce. The xml always reflected the correct orderRelevant value.
